before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
image: gradle:8.3-jdk20-alpine
stages:
  - test
  - build
build:
  stage: build
  script: ./gradlew build
test:
  stage: test
  script: ./gradlew test
